### PR TITLE
[BEEEP] Update bitwarden-ssh RustCrypto dependencies, fixing imports of various SSH keys

### LINKED ISSUE #17691: Cannot import OPENSSH key
### Steps To Reproduce

1. Go to "Add Item"
2. Choose "SSH Key"
3. A new SSH Key will be created
4. Copy your private key (e.g. ~/.ssh/id_rsa) to the clipboard
5. Click on the "Import key from clipboard" button next to the "Private Key" input field

### Expected Result

OpenSSH private key is copied into the field

### Actual Result

The key is not copied (the old one is still there) and a red popup appears with the message "An error has occurred"

### Screenshots or Videos

Image

### Additional Context

Installed via AppImage

### Operating System

Linux

### Operating System Version

Operating System: openSUSE Tumbleweed 20251124

### Installation method

Other

### Build Version

2025.11.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by quexten**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-27518

Fixes:
https://github.com/bitwarden/clients/issues/17028
https://github.com/bitwarden/clients/issues/14076

## 📔 Objective

Updates the `bitwarden-ssh` dependencies to `rc` releases from RustCrypto. This allows us to:
- Drop our PKCS5 patch crate
- Fix import of putty keys
- Fix import of various other broken keys (linewidth issues and others)

It also replaces the RSA crate that has a vulnerability (timing attack) - though, it is unlikely that this actually affects import / was abusable.

RSA key generation test vectors are broken because the underlying RSA generation algorithm changed with rustcrypto's massive re-implementation of RSA, hence new test keys are provided.

Note: This pins the dependencies to be different from the workspace crates, as those are not yet ready to be updated. Eventually we will update those bit-by-bit too and then drop the dependency pinning.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by addisonbeck — DISMISSED** [review]

File: crates/bitwarden-wasm-internal/build.sh [hunk 1]
```diff
@@ -43,10 +43,10 @@ fi
 # Build with MVP CPU target, two reasons:
 # 1. It is required for wasm2js support
 # 2. While webpack supports it, it has some compatibility issues that lead to strange results
-# Note that this requirest build-std which is an unstable feature,
+# Note that this requires build-std which is an unstable feature,
 # this normally requires a nightly build, but we can also use the
 # RUSTC_BOOTSTRAP hack to use the same stable version as the normal build
-RUSTFLAGS=-Ctarget-cpu=mvp RUSTC_BOOTSTRAP=1 cargo build -p bitwarden-wasm-internal -Zbuild-std=panic_abort,std --target wasm32-unknown-unknown ${RELEASE_FLAG} ${ENABLE_LICENSE_FEATURE}
+RUSTFLAGS='-Ctarget-cpu=mvp --cfg getrandom_backend="wasm_js"' RUSTC_BOOTSTRAP=1 cargo build -p bitwarden-wasm-internal -Zbuild-std=panic_abort,std --target wasm32-unknown-unknown ${RELEASE_FLAG} ${ENABLE_LICENSE_FEATURE}
```
Comment (dani-garcia) [inline crates/bitwarden-wasm-internal/build.sh:49]: This flag is already set in the cargo config, is it still needed here? https://github.com/bitwarden/sdk-internal/blob/main/.cargo/config.toml#L8

Comment (quexten) [reply crates/bitwarden-wasm-internal/build.sh:49]: Yeah, seems the flag in cargo.toml is not effective. Not setting it in the build script makes the build fail:
```
error: The wasm32-unknown-unknown targets are not supported by default; you may need to enable the "wasm_js" configuration flag. Note that enabling the `wasm_js` feature flag alone is insufficient. For more information see: https://docs.rs/getrandom/0.3.3/#webassembly-support
   --> /Users/quexten/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/getrandom-0.3.3/src/backends.rs:168:9
    |
168 | / ...   compile_error!(concat!(
169 | | ...       "The wasm32-unknown-unknown targets are not supported...
170 | | ...       you may need to enable the \"wasm_js\" configuration ...
171 | | ...       that enabling the `wasm_js` feature flag alone is ins...
172 | | ...       For more information see: \
173 | | ...       https://docs.rs/getrandom/", env!("CARGO_PKG_VERSION"...
174 | | ...   ));
    | |________^
```

Comment (dani-garcia) [reply crates/bitwarden-wasm-internal/build.sh:49]: Ah seems like RUSTFLAGS overrides all flags rather than append to them. We can leave this as is then.

**Review by addisonbeck — APPROVED** [review]
